### ISSUE TITLE
大佬，能上个例子不，有点看不懂😂

### ISSUE THREAD

**Issue by yangy996** [verarong/CommonOcrExtractor#1]

**Comment by verarong** [comment]
大部分的票据类型都实现好了，比如你现在有个后端的微服务（flask、fastapi等等），在app下面建个extractor文件夹，吧这些都丢进去，外面impot一下
from app.extractor.information_extraction import DataHandle
比较通用的ocr不定长文本识别用ctcloss，用下面这个
state, predict =
 DataHandle(ocr_score【识别的文本结果，list存储的多个】,
                          box【识别的文本框位置结果，list存储的多个】, 
                          score_【原始ctc的nparray结果，list存储的多个】, 
                          invoice_type【票据类型，参见config】,
                          invoice_direction_filter【通过lableme标注自动生成的字段位置filter配置，可以不传有默认的】, True).extract()
