### ISSUE TITLE
大佬，想问下invoice.config里面key_dicts是什么呀

### ISSUE THREAD

**Issue by yuricasi** [verarong/CommonOcrExtractor#2]
大佬，想问下invoice.config里面key_dicts是什么呀？我自己配置的所有要识别的中文的字典就可以吗？

**Comment by verarong** [comment]
> 大佬，想问下invoice.config里面key_dicts是什么呀？我自己配置的所有要识别的中文的字典就可以吗？

嗯嗯，一般主工程最后的ocr用ctcloss需要自定义识别的字符，这样输出是一个shape为字符数*不定长识别窗口数的矩阵，
