### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by QingfengBetter** [verarong/CommonOcrExtractor#3]
楼主 方便上传下app文件么，ALPHABET解析不到。
可以的话想加一下您的联系方式，沟通一下。

**Comment by verarong** [comment]
> 楼主 方便上传下app文件么，ALPHABET解析不到。
> 可以的话想加一下您的联系方式，沟通一下。

好的哈，回头我传一下，这个实际ALPHABET是ctcloss自定义所需要识别的字符，你训练ocr定义了多少字符就统一import进来
